base_url = "https://tokilabs.co"
compile_sass = true
build_search_index = true
title = "tokilabs"
generate_feeds = true
feed_filenames = ["rss.xml"]

taxonomies = [
]

[markdown]
highlight_code = true
highlight_theme = "kronuz"
